FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ["backend.csproj", "./"]
RUN dotnet restore "backend.csproj"

COPY . .

RUN dotnet publish "backend.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/out .

ENV ASPNETCORE_URLS="http://*:5020"

EXPOSE 5020
ENTRYPOINT ["dotnet", "backend.dll"]